### PR TITLE
added bash script that plots raw data automatically

### PR DESCRIPTION
**Pull request by sonyahanson**
just a quick PR so that we know what our data looks like

### CODE REVIEW

**Comment by jchodera** [comment]
Hm. Some of those plots are blank, like [this one](https://github.com/choderalab/fluorescence-assay-manuscript/blob/7edd37c1d0500878a4088f5aeb7a62888b714c70/analysis/rawdata/singlet/p38_8lig2_20160426_122008_280_340_TOP_120.png).

**Comment by jchodera** [comment]
In plots like [these](https://github.com/choderalab/fluorescence-assay-manuscript/blob/7edd37c1d0500878a4088f5aeb7a62888b714c70/analysis/rawdata/singlet/p38_8lig2_20160426_122008_ABS_280.png) all the interesting stuff happens at the high-concentration end.  I wonder if we want to focus in more on that concentration range once we figure out the noise floor?  Alternatively, we could think of a two-stage protocol where the measurement is performed again with a restricted range of concentrations?

**Comment by jchodera** [comment]
Oh!  I might be reading this wrong. Is one of the concentrations zero, but the x-range happens to show things such that all the action is in the right half of the plot?

**Comment by sonyahanson** [comment]
First Bayesian modeling result images and json files now available!

**Pull request merged**
