### PR TITLE
Updating analysis folder to have results from updated quickmodel run

### PR DESCRIPTION
**Pull request by sonyahanson**
First is 8lig dataset

### CODE REVIEW

**Comment by sonyahanson** [comment]
This all the new analyses.

**Comment by MehtapIsik** [comment]
I am confused about how many iterations of sampling was used for the updated analysis.

[Quickbayes.sh script](https://github.com/choderalab/fluorescence-assay-manuscript/blob/analysis_update/analysis/bayes/quickbayes.sh) seems to be using default sampling values of quickmodel (nsamples=1000, nthin=20, niter=20000).

But number of MCMC samples in analysis plots show 10000. Here is [one example](https://github.com/choderalab/fluorescence-assay-manuscript/blob/analysis_update/analysis/bayes/8ligs/delG_Bosutinib%20Isomer-CD-2017-04-13%200139.png).

**Comment by MehtapIsik** [comment]
Sonya and I discussed my concern above. I wanted to make a note here to clarify. 

The x-axis of DeltaG vs MCMC sample plots show value for `nsample`. Total number of iteration is niter, where `niter = nthin * nsample`. Default `nthin` values is 20. We currently believe MCMC samples (`nsample`) of 100 000-250 000 is needed for reproducible confidence intervals.

**Comment by sonyahanson** [comment]
Indeed. I have now updated [quickbayes.sh](https://github.com/choderalab/fluorescence-assay-manuscript/blob/analysis_update/analysis/bayes/quickbayes.sh) to reflect that the analyses in `/analysis/bayes/` were done with `--nsamples 10000` and not the defaults of quickmodel, exactly as Mehtap asked about in her first comment. And as she noted above, nsamples should be the same as the number of MCMC samples plotted in the output pngs, unless you change the defaults of nthin and niter.

At the point where we start running more samples, here 10,000 is feasible on a laptop, but towards 100,000 and 250,000, it is best to use the cluster, which is part of why I hadn't run everything at once using `quickbayes.sh`, and this ended up getting decoupled from the results files, sadly. I was using interactive sessions, but we should maybe start adding cluster submit scripts here...

**Pull request merged**
