### PR TITLE
Working on figures.

### PR DESCRIPTION
**Pull request by sonyahanson**
First adding spectra figure scripts, pngs, and svg.

### CODE REVIEW

**Comment by jchodera** [comment]
Let's make sure to use vector graphics (PDFs) instead of raster graphics (PNGs) for these plots when you render them in Python.

**Comment by sonyahanson** [comment]
Have beginnings drafts for Figures 1-4 now.

**Comment by jchodera** [comment]
This new figure is much closer!
simulated_fluorescence_cv_bias
Is it possible to more densely cover the Kd range? 

I'm also unclear on why we have a range that includes 0.02 nM, 0.2 nM, 2 nM, 200 nM, 8 uM---that seems like a really odd set of choices.

Are you using the Bayesian inference of the simulated experiments to get the CV and RB? I thought we wanted to use the assay predictor and just the statistics over the least-squares fits, since it's so much faster for assay design?

**Comment by jchodera** [comment]
Also, we don't need the different colored points if we're not going to include this plot:
simulated_fluorescence_kd_result

**Comment by jchodera** [comment]
Or was the idea that you would include both of those as top and bottom panels?

**Comment by jchodera** [comment]
Also, is the %CV for the Kd or the DeltaG? I think we're interested in the CV and RB for the DeltaG, not the Kd. 

We probably also need a horizontal line at 0%CV, and the %CV goes up to 200% even though no points are above 100%.

We may also want to more densely fill in the CV/RB plot since it looks pretty sparse (even if we don't fill in the P(Kd) plot).

**Comment by jchodera** [comment]
Thanks for updating!

In panel C, can you project histograms on the y-axis on the right side of the nuisance parameter traces, similar to what you've done for DeltaG?

I'd also make the trace about 80% as wide as the histogram part, which only need be 20% as wide.

**Comment by sonyahanson** [comment]
Last couple commits address #19 using e.g.:
```python
ax1.plot(range(0,len(data['F_PL'][0]),10),data['F_PL'][0][::10],color='C0')
```
in these lines:
https://github.com/choderalab/fluorescence-assay-manuscript/blob/figures/figures/Figure2/generate_analyze_figures.py#L115
https://github.com/choderalab/fluorescence-assay-manuscript/blob/figures/figures/Figure2/generate_analyze_figures.py#L154
https://github.com/choderalab/fluorescence-assay-manuscript/blob/figures/figures/Figure2/generate_analyze_figures.py#L212
https://github.com/choderalab/fluorescence-assay-manuscript/blob/figures/figures/Figure2/generate_analyze_figures.py#L280

**Comment by jchodera** [comment]
Instead of hard-coding in `::10` everywhere, can you make this a variable? e.g. `::nthin` where `nthin` is the thinning factor?

**Comment by sonyahanson** [comment]
Updated simulated fluoresce script `generate_protein_concentration_simulation_fig.py` so it is more programmatic and flexible.

Also updated so the figure shows 2 and 20 µM values instead of the middle 8 µM value.

simulated_fluorescence_p_1nm

**Comment by jchodera** [comment]
> Also updated so the figure shows 2 and 20 µM values instead of the middle 8 µM value.

This is much nicer, thanks!

Are the figure dimensions such that the font is the appropriate size (no smaller than 6 points) when embedded in the final figure?

**Comment by sonyahanson** [comment]
Merging this. Will make new PR for second set of figures.

**Pull request merged**
