### PR TITLE
Making draft of Figure 1.

### PR DESCRIPTION
**Pull request by sonyahanson**
Added data to be able to add first draft of figure 1.

### CODE REVIEW

**Comment by sonyahanson** [comment]
A first draft of figure 1 as generated from the data in this repo has been added.

**Comment by jchodera** [comment]
Awesome!  Is it this one?

Figure1

A few quick commments:
- Note that we need to make sure the rendered figures for publication are vector graphics (PDF) and not raster graphics (PNG, GIF, or JPEG).
- The text is way too small. For a full-page-width figure (7.5 inches), text should be no smaller than 6 points, ideally 9 points.
- What are the weird things going on in "Src - Bosutinib" with the huge jump, or "p38 - Gefitinib" (red line)?
- Do we want to have a single colorbar somewhere on the figure as a reference to what the colored traces mean?
- Now is a good time to standardize our naming conventions.  Is it "Bosutinib" or "bosutinib"?  Should we say "Src - bosutinib" or "Src:bosutinib"?

A great start!

**Comment by sonyahanson** [comment]
My To Do's here are:
     - Move titles to outside rows and columns, like here: http://stackoverflow.com/questions/25812255/row-and-column-headers-in-matplotlibs-subplots
      - Add in images of ligands as the row ‘titles’ using this: http://stackoverflow.com/questions/3765056/combine-picture-and-plot-with-python-matplotlib
     - Make colorbars as generated by python like here: http://stackoverflow.com/questions/13784201/matplotlib-2-subplots-1-colorbar
      - Make it so that we have a choice about which section is being plotted

Adding your To Do's:
    - Make figure vector graphic: e.g. PDF, would EPS do?
    - Increase text size (moving the titles to rows and columns rather than for individual frame will automatically make this better)

Answering your questions:
- I agree, I think we should stick with e.g. 'bosutinib' not sure about "Src - bosutinib" or "Src:bosutinib". This syntax will not ultimately be used in this figure, but may be relevant to the rest of the paper.
- The weird jump in Src - bosutinib is that the signal was read as 'OVER' in the infinite. This is part of why I want to choose which section is being plotted more explicitly, as I think right now the data here is for gain 120, and I think this is not a problem for gain 100 data. I'm not sure what has happened in the case of the gefitinib data.

**Comment by jchodera** [comment]
> - Make figure vector graphic: e.g. PDF, would EPS do?

EPS works, but PDF is easy too: [example](http://matplotlib.org/examples/pylab_examples/multipage_pdf.html)

>  not sure about "Src - bosutinib" or "Src:bosutinib". This syntax will not ultimately be used in this figure, but may be relevant to the rest of the paper.

Yep, that's why its' good to decide now.  I like `Src:bosutinib` if there is no reason to prefer otherwise.

> The weird jump in Src - bosutinib is that the signal was read as 'OVER' in the infinite. This is part of why I want to choose which section is being plotted more explicitly, as I think right now the data here is for gain 120, and I think this is not a problem for gain 100 data. I'm not sure what has happened in the case of the gefitinib data.

Do we need to re-collect the gefitinib data?

**Comment by sonyahanson** [comment]
> Do we need to re-collect the gefitinib data?

I assume this is referring to the p38:gefitinib data (this syntax is fine with me) for which we already have three sets of data (1x1gain and 2x2gains):
allp38
Also, similarly for the Bosutinib data:
bos-more

**Comment by sonyahanson** [comment]
Merging this, and moving the To Do list to an issue.

**Pull request merged**
